### PR TITLE
do not create unnecessary alb lister rules

### PR DESCRIPTION
**Pull request by Andrey9kin**

### CODE REVIEW

**Comment by cageyv** [comment]
that functionality is currently being used and it is necessary in order to replace the ECS Service in case of recreating

**Comment by cageyv** [comment]
```
        content {
          arn    = target_group.key
          weight = target_group.value
        }
```
This part will be different depends of number of target groups

**Comment by Andrey9kin** [comment]
@cageyv my primary problem is the fact that it creates a rule per DNS name when it can very well match with the list of the DNS names.  I can leave both resources be if needed

**Comment by cageyv** [comment]
@Andrey9kin 
Yes it is
The reason is the limited number of hostnames per 1 rule
Only 5 domains can be created per rule

"Condition values limit (5 per rule)"
Details here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html

It would be very interesting if we split domains in groups of 5 in order to get around this limit
`chunklist(list, chunk_size)` can probably solve this case

**Pull request closed without merging**
